### PR TITLE
Update README.md

### LINKED ISSUE #162: Broken link in README.md
https://github.com/ole-vi/treehouse-builder/blame/master/README.md#L80

Link to our wiki is broken 😄

### PR DESCRIPTION
**Pull request by 7ayushgupta**
Fixes #162

### CODE REVIEW

**Comment by 7ayushgupta** [comment]
Why is the test failing? I just changed the link in the `README.md`.
Sorry, but I am a complete beginner at such projects, as well as open-source.
Please care to help out :smile:

**Comment by dogi** [comment]
@7ayushgupta it has to do with the secrets which are part of our travis repo ...

**Comment by 7ayushgupta** [comment]
So, what can I change to pass the checks?

**Comment by dogi** [comment]
Good question
think we need to refactor `.travis.yml`
so that build works on forks ...

**Comment by dogi** [comment]
@7ayushgupta look at https://github.com/ole-vi/treehouse-builder/pull/176

**Pull request merged**
